-- local format_sync_grp = vim.api.nvim_create_augroup("GoImport", {})
--
--
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*.go",
--   group = format_sync_grp,
--   callback = function ()
--       --vim.cmd('silent! GoImports')
--       vim.cmd('silent! GoFmt')
--   end
-- })
